spring:
  data:
    mongodb:
      uri: mongodb://kodiatech:kodiapwd@localhost:27017/consultant_db
      ##log
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    problemdetails:
      enabled: true
  jackson:
    time-zone: Europe/Paris

## corse source lorsque j'accede
cors:
  allowed-origins: http://localhost:4200


## comme je n'ai pas de mot de passe et user donc je laisse comme
## bdd est creee automatiquement par mongo
## https://stackoverflow.com/questions/56371736/spring-boot-mongo-db-yml-configuration

logging:
  level:
    datasource-query-logger: INFO
    org:
      springframework:
        data: DEBUG
        security: DEBUG
        web: ERROR
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
  ## genereted file log
  path: concretepage/logs


server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false


##
kodiatech:
  app:
    access-expiration: 900000   # 15 min
    refresh-expiration: 86400000 # 24h
    secretkey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
key:
  name: description here
